name: Nightly Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wpf:
    name: Build WPF
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1

      - run: cargo build --release
        working-directory: searchengine

      - run: copy searchengine\target\release\searchengine.dll Anything-UI-WPF\

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - run: dotnet build -c Release
        working-directory: Anything-UI-WPF

      - uses: actions/upload-artifact@v7
        with:
          name: wpf-build
          path: Anything-UI-WPF/bin/Release/
          retention-days: 7

  gtk:
    name: Build GTK
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install dependencies
        run: dnf install -y gtk4-devel libadwaita-devel

      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1

      - run: cargo build --release
        working-directory: Anything-UI-GTK

      - uses: actions/upload-artifact@v7
        with:
          name: gtk-build
          path: Anything-UI-GTK/target/release/anything-gui
          retention-days: 7
